newfies/dnc/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns


urlpatterns = patterns('dnc.views',
                       # DNC urls
                       (r'^module/dnc_list/$', 'dnc_list'),
                       (r'^module/dnc_list/add/$', 'dnc_add'),
                       (r'^module/dnc_list/contact_count/$', 'get_dnc_contact_count'),
                       (r'^module/dnc_list/del/(.+)/$', 'dnc_del'),
                       (r'^module/dnc_list/(.+)/$', 'dnc_change'),

                       # DNC Contacts urls
                       (r'^module/dnc_contact/$', 'dnc_contact_list'),
                       (r'^module/dnc_contact/add/$', 'dnc_contact_add'),
                       (r'^module/dnc_contact_import/$', 'dnc_contact_import'),
                       (r'^module/dnc_contact/export/$', 'dnc_contact_export'),
                       (r'^module/dnc_contact/export_view/$', 'dnc_contact_export_view'),
                       (r'^module/dnc_contact/del/(.+)/$', 'dnc_contact_del'),
                       (r'^module/dnc_contact/(.+)/$', 'dnc_contact_change'),
                       )

newfies/newfies_dialer/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns, url
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
from mod_registration.urls import urlpatterns as urlpatterns_mod_registration
# from agent.urls import urlpatterns as urlpatterns_agent
# from callcenter.urls import urlpatterns as urlpatterns_callcenter
from mod_sms.urls import urlpatterns as urlpatterns_mod_sms
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib import admin
import os


admin.autodiscover()
dajaxice_autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
                       (r'^logout/$', 'frontend.views.logout_view'),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
                       (r'^admin_tools/', include('admin_tools.urls')),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),
                       #(r'^sentry/', include('sentry.web.urls')),
                       #(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
                       url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
                       )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_mod_registration
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
# urlpatterns += urlpatterns_agent
# urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_mod_sms

urlpatterns += patterns('',
                        (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
                         'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                        )


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

newfies/dnc/models.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django.db import models
from django.utils.translation import ugettext_lazy as _


class DNC(models.Model):

    """This defines the Do Not Call List

    **Attributes**:

        * ``name`` - List name.

    **Relationships**:

        * ``user`` - Foreign key relationship to the User model.

    **Name of DB table**: dnc_list
    """
    name = models.CharField(max_length=50, blank=False, null=True, verbose_name=_("name"),
                            help_text=_("Enter a DNC list name"))
    description = models.TextField(null=True, blank=True, help_text=_("DNC notes"))
    user = models.ForeignKey('auth.User', related_name='DNC owner')

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.name)

    class Meta:
        permissions = (
            ("view_dnc", _('can see Do Not Call list')),
        )
        db_table = "dnc_list"
        verbose_name = _("Do Not Call list")
        verbose_name_plural = _("Do Not Call lists")

    def dnc_contacts_count(self):
        """This will return a count of the contacts in the dnc"""
        return DNCContact.objects.filter(dnc=self.id).count()
    dnc_contacts_count.allow_tags = True
    dnc_contacts_count.short_description = _('DNC contacts')


class DNCContact(models.Model):

    """This defines the Do Not Call Contact for each DNC List

    **Attributes**:

        * ``phone_number`` - Phone number
        * ``dnc`` - DNC List

    **Relationships**:

        * ``dnc`` - Foreign key relationship to the DNC model.

    **Name of DB table**: dnc_contact
    """
    dnc = models.ForeignKey(DNC, verbose_name=_("Do Not Call List"))
    phone_number = models.CharField(max_length=120, db_index=True, verbose_name=_("phone number"))

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True,)

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.phone_number)

    class Meta:
        permissions = (
            ("view_dnc_contact", _('can see Do Not Call contact')),
        )
        db_table = "dnc_contact"
        verbose_name = _("Do Not Call contact")
        verbose_name_plural = _("Do Not Call contacts")

newfies/dnc/forms.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2015 Star2Billing S.L.
#
# The primary maintainer of this project is
# Arezqui Belaid <info@star2billing.com>
#

from django import forms
from django.forms import ModelForm, Textarea
from django.utils.translation import ugettext_lazy as _
from django.forms.util import ErrorList
from dnc.models import DNC, DNCContact
from dialer_contact.forms import FileImport
from mod_utils.forms import Exportfile

# from django.core.urlresolvers import reverse
from mod_utils.forms import SaveUserModelForm, common_submit_buttons
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Div, HTML


class DNCListForm(SaveUserModelForm):

    """DNC List Form"""

    class Meta:
        model = DNC
        fields = ['name', 'description']
        exclude = ('user',)
        widgets = {
            'description': Textarea(attrs={'cols': 26, 'rows': 3}),
        }

    def __init__(self, *args, **kwargs):
        super(DNCListForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'well'
        self.helper.layout = Layout(
            Div(
                Div(Fieldset('', 'name', 'description', css_class='col-md-6')),
            ),
        )
        if self.instance.id:
            common_submit_buttons(self.helper.layout, 'update')
        else:
            common_submit_buttons(self.helper.layout)


class DNCContactSearchForm(forms.Form):

    """Search Form on Contact List"""
    phone_number = forms.IntegerField(label=_('Phone Number'), required=False)
    dnc = forms.ChoiceField(label=_('Do Not Call list'), required=False)

    def __init__(self, user, *args, **kwargs):
        super(DNCContactSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'well'
        self.helper.layout = Layout(
            Div(
                Div('phone_number', css_class='col-md-4'),
                Div('dnc', css_class='col-md-4'),
                css_class='row'
            ),
        )
        common_submit_buttons(self.helper.layout, 'search')
        # To get user's dnc list
        if user:
            dnc_list_user = []
            dnc_list_user.append((0, '---'))
            for i in DNC.objects.values_list('id', 'name').filter(user=user).order_by('-id'):
                dnc_list_user.append((i[0], i[1]))

            self.fields['dnc'].choices = dnc_list_user


class DNCContactForm(ModelForm):

    """DNCContact ModelForm"""

    class Meta:
        model = DNCContact
        fields = ['dnc', 'phone_number']

    def __init__(self, user, *args, **kwargs):
        super(DNCContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'well'
        self.helper.layout = Layout(
            Div(
                Div(Fieldset('', 'dnc', 'phone_number', css_class='col-md-6')),
            ),
        )
        if user:
            self.fields['dnc'].choices = DNC.objects.values_list('id', 'name').filter(user=user).order_by('id')

        if self.instance.id:
            common_submit_buttons(self.helper.layout, 'update')
        else:
            common_submit_buttons(self.helper.layout)

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', None)
        try:
            int(phone_number)
        except:
            msg = _('Please enter a valid phone number')
            self._errors['phone_number'] = ErrorList([msg])
            del self.cleaned_data['phone_number']
        return phone_number


def get_dnc_list(user):
    """get dnc list for ``dnc_list`` field which is used by DNCContact_fileImport
    & DNCContact_fileExport
    """
    result_list = []
    for dnc in DNC.objects.filter(user=user).order_by('id'):
        contacts_in_dnc = dnc.dnc_contacts_count()
        nbcontact = " -> %d contact(s)" % (contacts_in_dnc)
        dnc_string = dnc.name + nbcontact
        result_list.append((dnc.id, dnc_string))
    return result_list


class DNCContact_fileImport(FileImport):

    """Admin Form : Import CSV file with DNC list"""
    dnc_list = forms.ChoiceField(label=_("DNC List"), required=True, help_text=_("select DNC list"))

    def __init__(self, user, *args, **kwargs):
        super(DNCContact_fileImport, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'well'
        self.helper.layout = Layout(
            Div(
                Div(Fieldset('', 'dnc_list', 'csv_file', css_class='col-md-6')),
            ),
        )
        common_submit_buttons(self.helper.layout, 'import')

        # To get user's dnc_list list
        # and not user.is_superuser
        if user:
            self.fields['dnc_list'].choices = get_dnc_list(user)
            self.fields['csv_file'].label = _('Upload CSV file')


class DNCContact_fileExport(Exportfile):

    """
    DNC Contact Export
    """
    dnc_list = forms.ChoiceField(label=_("DNC list"), required=True, help_text=_("select DNC list"))

    def __init__(self, user, *args, **kwargs):
        super(DNCContact_fileExport, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'well'
        self.helper.layout = Layout(
            Div(
                Div(Fieldset('', 'dnc_list', css_class='col-md-6')),
                css_class='row'
            ),
            Div(
                Div(HTML("""
                    <b>%s : </b>
                    <div class="btn-group" data-toggle="buttons">
                        {% for choice in form.export_to.field.choices %}
                        <label class="btn btn-default">
                            <input name='{{ form.export_to.name }}' type='radio' value='{{ choice.0 }}'/> {{ choice.1 }}
                        </label>
                        {% endfor %}
                    </div>
                   """ % _('Export to')), css_class='col-md-6'),
                css_class='row'
            ),
        )
        common_submit_buttons(self.helper.layout, 'add')

        # To get user's dnc_list list
        if user:  # and not user.is_superuser
            self.fields['dnc_list'].choices = get_dnc_list(user)

newfies/dnc/templates/dnc/dnc_contact/change.html
{% extends "frontend/master.html" %}
{% load i18n crispy_forms_tags %}

{% block content_header %}
    <h1>{{ action|capfirst }} {% trans "dnc"|upper %} {% trans "contact"|title %}
        <small>{% trans "add DNC contact details"|capfirst %}</small>
    </h1>
{% endblock %}

{% block content %}
    {% crispy form form.helper %}
{% endblock %}

newfies/dnc/templates/dnc/dnc_contact/export_dnc_contact.html
{% extends "frontend/master.html" %}
{% load i18n crispy_forms_tags %}

{% block bootstrap_switch_js %}
{% endblock %}

{% block content_header %}
    <h1>{% trans "export DNC contacts"|capfirst %} <small>{% trans "export list of DNC contacts"|capfirst %}</small></h1>
{% endblock %}

{% block content %}
    {% crispy form form.helper %}
{% endblock %}

newfies/dnc/templates/dnc/dnc_contact/import_dnc_contact.html
{% extends "frontend/master.html" %}
{% load i18n crispy_forms_tags %}

{% block content_header %}
    <h1>{% trans "import DNC contacts"|capfirst %} <small>{% trans "import list of DNC contacts by uploading CSV files"|capfirst %}</small></h1>
{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped table-bordered table-condensed">
    <caption><h3>{% trans "sample file"|title %}</h3></caption>
    <thead>
    <tr>
        <th>{% trans "contact number"|title %}</th>
    </tr>
    </thead>
    <tr>
        <td>650784355</td>
    </tr>
    <tr>
        <td>650723032</td>
    </tr>
    </table>
</div>

<br/>

{% crispy form form.helper %}

{% if success_import_list %}
<div class="table-responsive">
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th>{% trans "DNC contact(s) imported (display max 100)" %} :</th>
        </tr>
        {% for row in success_import_list %}
        <tr>
            <td>
                {{ row }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

{% if type_error_import_list %}
<br/>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th>{% trans "type mismatch"|title %} :</th>
        </tr>
        {% for row in type_error_import_list %}
        <tr>
            <td>
                {{ row }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

{% endblock %}

newfies/dnc/templates/dnc/dnc_contact/list.html
{% extends "frontend/master.html" %}
{% load i18n common_tags pagination_tags crispy_forms_tags %}

{% block content_header %}
    <h1>{% trans "DNC" %} {% trans "contacts"|title %} <small>{% trans "list, add and edit Do Not Call contacts"|capfirst %}</small></h1>
{% endblock %}

{% block content %}
<div id="form_collapse" class="collapse">
    {% crispy form form.helper %}
</div>
{% include "frontend/common_search_toggle_button.html" %}
<div>&nbsp;</div>
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans "action"|capfirst %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% if perms.dnc.delete_dnccontact %}
                    <li><a href="#" onclick="delete_button()">{% trans "delete selected"|title %}</a></li>
                {% endif %}
                <li>
                    <a href="export_view/">{% trans "DNC" %} {% trans "export"|capfirst %}</a>
                </li>
            </ul>
        </div>
        {% if perms.dnc.add_dnccontact %}
            <button type="button" class="btn btn-info" onclick="add_button()">
                <i class="fa fa-plus"></i> {% trans "add"|title %}
            </button>
        {% endif %}
    </div>
</div>

<br/>

<div class="row">
    <div class="col-md-12">
        <form method="POST" role="form" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                        <th>{% sort_link DNC_CONTACT_COLUMN_NAME.id|capfirst col_name_with_order.id %}</th>
                        <th>{% sort_link DNC_CONTACT_COLUMN_NAME.dnc|capfirst col_name_with_order.dnc %}</th>
                        <th>{% sort_link DNC_CONTACT_COLUMN_NAME.phone_number|capfirst col_name_with_order.phone_number %}</th>
                        <th>{% sort_link DNC_CONTACT_COLUMN_NAME.date|capfirst col_name_with_order.updated_date %}</th>
                        <th>{% trans 'action'|capfirst %}</th>
                    </tr>
                    </thead>
                    {% if phone_number_list %}
                        {% autopaginate all_phone_number_list newfies_page_size %}
                        {% for row in phone_number_list %}
                            <tr>
                                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                                <td>{{ row.id }}</td>
                                <td>{{ row.dnc__name }}</td>
                                <td>{{ row.phone_number }}</td>
                                <td>{{ row.updated_date }}</td>
                                <td>
                                    {% if perms.dnc.change_dnccontact %}
                                        <a href="{{ row.id }}/" title="{% trans 'update DNC contact'|title %}"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if perms.dnc.delete_dnccontact %}
                                        <a id="id_delete_confirm" href="del/{{ row.id }}/" title="{% trans 'delete DNC contact'|title %}"><i class="fa fa-trash-o"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="6" align="center">
                                {% trans "no records found"|title %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="text-right">
                {% trans "total"|title %} : {{ total_phone_numbers }}
            </div>
            {% if phone_number_list %}
                {% paginate %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}